import * as THREE from './three.module.js';
import {level,circuits} from './levels.js';
import {at,yaw,angle,curvature,nearest,advance,wrap,LENGTH,samples,district,districts,driftZones,circularDistance,TRACK_HALF_WIDTH} from './track.js';
import {scene,makeCar,ambientCars,collisionBodies,updateStartLights,updateWorldSetpieces} from './world.js';
import {createPostFX,createAtmosphere,createSkidMarks} from './effects.js';
import {MusicDirector} from './music.js';
import {medalNames,earnedLicense,licenseTitle} from './progression.js';
import {BOOST_MAX,boostFromBank,spendBoost} from './boost.js';
const $=id=>document.getElementById(id),clamp=THREE.MathUtils.clamp;
document.body.classList.add('world-'+level.id);document.documentElement.style.setProperty('--accent',level.accent);document.documentElement.style.setProperty('--accent-2',level.accent2);document.querySelectorAll('.primary').forEach(button=>button.style.backgroundColor=level.accent);$('themeColor').content=level.accent;$('worldTheme').innerHTML=level.theme.replace(' // ',' <b>//</b> ');$('worldMark').textContent=level.mark;$('circuitEyebrow').textContent=level.name+' / DRIFT RACING';$('circuitTagline').textContent=level.tagline;$('circuitPromise').textContent=level.promise;$('missionLabel').textContent=level.name+' / DRIFT RUN';$('missionTitle').textContent=level.brief;$('missionText').textContent=level.mission;$('briefLabel').textContent='RACE BRIEFING / '+level.name;$('briefTitle').textContent=level.brief;$('briefBody').textContent=level.briefBody;document.querySelector(`[data-level="${level.id}"]`)?.setAttribute('aria-current','true');document.title='NEON BREACH — '+level.name;
$('circuitMeta').innerHTML=`CIRCUIT ${level.number} <span>•</span> ${(LENGTH/1000).toFixed(2)} KM <span>•</span> 03 LAPS`;
let settings={volume:35,musicVolume:38,quality:'auto',difficulty:'casual',effects:true,ghosts:true,touch:matchMedia('(pointer:coarse)').matches,reducedMotion:matchMedia('(prefers-reduced-motion:reduce)').matches};try{Object.assign(settings,JSON.parse(localStorage.getItem('neon-race-settings')||'{}'))}catch{}
for(const k in settings)$(k)[typeof settings[k]==='boolean'?'checked':'value']=settings[k];
let renderer;try{renderer=new THREE.WebGLRenderer({canvas:$('world'),antialias:true,powerPreference:'high-performance'})}catch{$('error').classList.remove('hidden');throw Error('WebGL unavailable')}
renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.2;
const camera=new THREE.PerspectiveCamera(64,innerWidth/innerHeight,.1,1500),player=makeCar(level.edgeB),rivals=[makeCar(level.edgeA,27),makeCar(0xffbc5b,4),makeCar(0x9b8cff,88)],ghost=makeCar(level.edgeB,0),colors=[level.accent2,'#ffc265','#a58cff'];ghost.visible=false;ghost.traverse(o=>{if(!o.isMesh)return;o.material=o.material.clone();o.material.transparent=true;o.material.opacity=.19;o.material.depthWrite=false});
// Real headlamps follow the car's pitch without costly shadow maps.
for(const x of [-.7,.7]){const headlamp=new THREE.SpotLight(0x9beaff,420,38,.34,.75,1.5);headlamp.position.set(x,.78,2.7);headlamp.target.position.set(x,-.2,22);player.userData.body.add(headlamp,headlamp.target)}
const postFX=createPostFX(renderer),atmosphere=createAtmosphere(scene,level),skidMarks=createSkidMarks(scene);
let state='menu',previous='menu',t=.982,progress=-.018,speed=0,heading=0,velocityHeading=0,time=0,countdown=3.1,toastTime=0,lastHit=0,best=null,bestScore=0,totalScore=0,chainScore=0,flow=0,boostCharge=0,isBoosting=false,boostLatch=false,combo=1,comboBonus=0,chainGrace=0,driftAngle=0,driftTime=0,driftMilestone=0,isDrifting=false,countersteering=false,offTrack=false,zoneCooldown=0,riskCooldown=0,nearMissCooldown=0,shake=0,lastLap=0,lapStarted=0,laps=[],sector='',checkpoint=0,setpieceLap=-1,cleanTime=0,lastComboStep=0,ghostLap=[],ghostSampleAt=0,ghostIndex=0,ghostRecord={time:Infinity,samples:[]},stats={bestChain:0,apex:0,contacts:0,wallKisses:0,nearMisses:0,perfectExits:0,boostsUsed:0};
const music=new MusicDirector(status=>{if(status==='unavailable')$('audioStatus').textContent='Music unavailable. Driving is still available.';else $('audioStatus').textContent=status==='loading'?'Loading soundtrack…':'Soundtrack by Tomasz Kucza'},level.id);music.setVolume(settings.musicVolume);let soundEnabled=true;
let brakeActive=false,lastPlace=4,visualSteer=0,flooded=false,drafting=false,blackoutActive=false,mechanicCue='',autoQuality=matchMedia('(pointer:coarse)').matches?'low':'high',hudAccumulator=0,qualityTime=0,qualityFrames=0;
let ai=[.986,.990,.994],aiSpeeds=[0,0,0],aiLanes=[-4.5,0,4.5],keys={},held={},audio,engine,engineGain,motor,motorGain,tyre,tyreGain,tyreFilter,noiseBuffer,soundTestUntil=0,soundStatusTimer,soundTestTrack='intro',padButtons=[];let last=performance.now(),raceAccumulator=0;
try{best=Number(localStorage.getItem(level.record+'-time-best'))||null}catch{}
try{bestScore=Number(localStorage.getItem(level.record+'-drift-best'))||0}catch{}
try{const saved=JSON.parse(localStorage.getItem(level.record+'-lap-ghost')||'null');if(saved?.samples?.length>20&&saved.time>0)ghostRecord=saved}catch{}
const readLicense=c=>{try{return clamp(Number(localStorage.getItem(c.record+'-license'))||0,0,3)}catch{return 0}};
let licenses=circuits.map(readLicense);
function renderLicenseBoard(){licenses=circuits.map(readLicense);$('licenseBoard').innerHTML=`<span>DRIVER LICENSE <strong>${licenseTitle(licenses)}</strong></span><div class="licenseMarks">${circuits.map((c,i)=>`<i class="${medalNames[licenses[i]].toLowerCase()}" title="${c.name}: ${medalNames[licenses[i]]}" aria-label="${c.name}: ${medalNames[licenses[i]]}"></i>`).join('')}</div>`}
renderLicenseBoard();
$('recordSummary').textContent=best||bestScore?`PERSONAL BEST / ${best?format(best):'--:--.-'} / ${bestScore.toLocaleString()} PTS`:'NO RECORD / FIRST RUN';
const nextLevel=circuits[(circuits.indexOf(level)+1)%circuits.length];$('nextCircuit').textContent='NEXT / '+nextLevel.name;$('nextCircuit').onclick=()=>location.search='?level='+nextLevel.id;
function audioStart(){try{audio??=new AudioContext();audio.resume();music.unlock(audio);$('sound').textContent=soundEnabled?'SOUND ON':'SOUND OFF';if(!engine){engine=audio.createOscillator();engineGain=audio.createGain();engine.type='sawtooth';engineGain.gain.value=0;const filter=audio.createBiquadFilter();filter.type='lowpass';filter.frequency.value=650;engine.connect(filter).connect(engineGain).connect(audio.destination);engine.start();motor=audio.createOscillator();motorGain=audio.createGain();motor.type='sine';motorGain.gain.value=0;motor.connect(motorGain).connect(audio.destination);motor.start();noiseBuffer=audio.createBuffer(1,audio.sampleRate,audio.sampleRate);const data=noiseBuffer.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=Math.random()*2-1;tyre=audio.createBufferSource();tyre.buffer=noiseBuffer;tyre.loop=true;tyreFilter=audio.createBiquadFilter();tyreFilter.type='bandpass';tyreFilter.frequency.value=level.id==='cryoline'?2500:level.id==='solara'?1250:1800;tyreFilter.Q.value=level.id==='cryoline'?4:2.8;tyreGain=audio.createGain();tyreGain.gain.value=0;tyre.connect(tyreFilter).connect(tyreGain).connect(audio.destination);tyre.start()}}catch{}}
function beep(freq=220,duration=.1){audioStart();if(!settings.volume||!soundEnabled)return;if(!audio)return;const o=audio.createOscillator(),g=audio.createGain();o.type='triangle';o.frequency.value=freq;g.gain.setValueAtTime(settings.volume/100*.12,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+duration)}
function impact(){music.duckFor();if(!audio||!noiseBuffer||!settings.volume||!soundEnabled)return;const n=audio.createBufferSource(),g=audio.createGain();n.buffer=noiseBuffer;g.gain.setValueAtTime(settings.volume/100*.22,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.18);n.connect(g).connect(audio.destination);n.start();n.stop(audio.currentTime+.2)}
function soundTestLabel(label,duration=1400){$('soundTestStatus').textContent='Testing '+label+'…';soundEnabled=true;$('sound').textContent='SOUND ON';clearTimeout(soundStatusTimer);soundStatusTimer=setTimeout(()=>{if(!soundTestUntil)$('soundTestStatus').textContent='Ready. Choose a channel.'},duration)}
function testEngineSound(){audioStart();if(!audio)return;soundTestLabel('engine sweep');const o=audio.createOscillator(),sub=audio.createOscillator(),g=audio.createGain(),now=audio.currentTime;o.type='sawtooth';sub.type='sine';o.frequency.setValueAtTime(72,now);o.frequency.exponentialRampToValueAtTime(290,now+1.15);sub.frequency.setValueAtTime(42,now);sub.frequency.exponentialRampToValueAtTime(130,now+1.15);g.gain.setValueAtTime(.001,now);g.gain.exponentialRampToValueAtTime(Math.max(.001,settings.volume/100*.08),now+.08);g.gain.exponentialRampToValueAtTime(.001,now+1.25);o.connect(g);sub.connect(g);g.connect(audio.destination);o.start();sub.start();o.stop(now+1.3);sub.stop(now+1.3)}
function testDriftSound(){audioStart();if(!audio||!noiseBuffer)return;soundTestLabel('tyre scrub');const n=audio.createBufferSource(),filter=audio.createBiquadFilter(),g=audio.createGain(),now=audio.currentTime;n.buffer=noiseBuffer;filter.type='bandpass';filter.frequency.setValueAtTime(1100,now);filter.frequency.linearRampToValueAtTime(2300,now+.8);filter.Q.value=2.4;g.gain.setValueAtTime(Math.max(.001,settings.volume/100*.08),now);g.gain.exponentialRampToValueAtTime(.001,now+.9);n.connect(filter).connect(g).connect(audio.destination);n.start();n.stop(now+.95)}
$('testEngine').onclick=testEngineSound;$('testDrift').onclick=testDriftSound;$('testImpact').onclick=()=>{audioStart();soundTestLabel('impact');impact()};$('testCue').onclick=()=>{soundTestLabel('race cue');beep(220,.12);setTimeout(()=>beep(330,.12),180);setTimeout(()=>beep(560,.22),360)};$('testMusic').onclick=()=>{audioStart();soundEnabled=true;music.setEnabled(true);soundTestTrack=soundTestTrack==='intro'?'race':'intro';soundTestUntil=performance.now()+6000;soundTestLabel(soundTestTrack+' music · 6 seconds',6200);music.setPhase(soundTestTrack)};
function show(id,on){$(id).classList.toggle('hidden',!on)}function juice(type){if(!settings.effects||settings.reducedMotion)return;document.body.classList.remove(type);void document.body.offsetWidth;document.body.classList.add(type);setTimeout(()=>document.body.classList.remove(type),type==='impact'?240:420)}function rumble(strength=.35,duration=90){try{navigator.getGamepads?.()[0]?.vibrationActuator?.playEffect('dual-rumble',{duration,strongMagnitude:strength,weakMagnitude:strength*.65});if(settings.touch)navigator.vibrate?.(Math.min(duration,80))}catch{}}function toast(s){$('toast').textContent=s;toastTime=2.5;show('toast',true);juice('toast-pop')}
function releaseAll(){keys={};held={};for(const id of ['left','right','brake','boost','drift'])$(id).classList.remove('held')}
const activePad=()=>[...(navigator.getGamepads?.()||[])].find(Boolean),keyboardHint='Steer with A / D. Hold SHIFT to drift and countersteer before release. A clean bank charges boost; hold E to deploy it. SPACE snaps the handbrake.',gamepadHint='Steer with the left stick and feather RT. Hold A, X, or RB to drift, then settle the car to bank charge. Hold LB to boost; B snaps the handbrake.',touchHint='Steer with the left and right pads. Hold DRIFT, countersteer, and release cleanly to charge BOOST. Auto-acceleration is enabled.';
function setInputMode(mode){$('inputMode').textContent=mode;document.body.classList.toggle('gamepad-active',mode==='GAMEPAD');$('controlHint').textContent=mode==='GAMEPAD'?gamepadHint:mode==='TOUCH'?touchHint:keyboardHint}
function readControls(){const pad=activePad(),raw=pad?.axes?.[0]||0,dead=Math.abs(raw)>.12?Math.sign(-raw)*Math.pow((Math.abs(raw)-.12)/.88,1.35):0,padThrottle=pad?.buttons?.[7]?.value||0,padBrake=pad?.buttons?.[6]?.value||0,padHandbrake=!!pad?.buttons?.[1]?.pressed,padBoost=!!pad?.buttons?.[4]?.pressed,padDrift=!!(pad?.buttons?.[0]?.pressed||pad?.buttons?.[2]?.pressed||pad?.buttons?.[5]?.pressed);const keySteer=(keys.KeyA||keys.ArrowLeft||held.left?1:0)-(keys.KeyD||keys.ArrowRight||held.right?1:0),keyThrottle=keys.KeyW||keys.ArrowUp||settings.touch?1:0,keyBrake=keys.KeyS||keys.ArrowDown||held.brake?1:0,keyHandbrake=!!keys.Space,keyBoost=!!(keys.KeyE||held.boost),keyDrift=!!(keys.ShiftLeft||keys.ShiftRight||held.drift);if(pad&&(Math.abs(dead)>.02||padThrottle>.02||padBrake>.02||padDrift||padHandbrake||padBoost))setInputMode('GAMEPAD');return{steer:clamp(keySteer+dead,-1,1),throttle:Math.max(keyThrottle,padThrottle),brake:Math.max(keyBrake,padBrake),handbrake:keyHandbrake||padHandbrake,boost:keyBoost||padBoost,drift:keyDrift||padDrift||keyHandbrake||padHandbrake}}
function pollGamepadActions(){const pad=activePad();if(!pad){padButtons=[];return}const current=[...pad.buttons].map(b=>b.pressed),pressed=i=>current[i]&&!padButtons[i];if(pressed(9)){if(state==='settings')$('resume').click();else pause()}if(pressed(0)){if(state==='menu')$('start').click();else if(state==='brief')$('deploy').click();else if(state==='settings')$('resume').click();else if(state==='end')$('retry').click()}if(pressed(3)&&state==='race')recenter();padButtons=current}
window.addEventListener('gamepadconnected',()=>{setInputMode('GAMEPAD');toast('GAMEPAD LINKED')});window.addEventListener('gamepaddisconnected',()=>{setInputMode(settings.touch?'TOUCH':'KEYBOARD');padButtons=[]});setInputMode(activePad()?'GAMEPAD':settings.touch?'TOUCH':'KEYBOARD');
function effectiveQuality(){return settings.quality==='auto'?autoQuality:settings.quality}
function config(){const quality=effectiveQuality(),ratio=Math.min(devicePixelRatio,quality==='high'?1.6:1);music.setVolume(settings.musicVolume);renderer.setPixelRatio(ratio);renderer.setSize(innerWidth,innerHeight);postFX.resize(innerWidth*ratio,innerHeight*ratio);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();document.body.classList.toggle('no-effects',!settings.effects||settings.reducedMotion);document.body.classList.toggle('reduced-motion',settings.reducedMotion);document.body.classList.toggle('touch-mode',settings.touch);show('controls',settings.touch&&state==='race')}
for(const k in settings)$(k).addEventListener('change',()=>{settings[k]=typeof settings[k]==='boolean'?$(k).checked:$(k).value;try{localStorage.setItem('neon-race-settings',JSON.stringify(settings))}catch{}if(k==='touch'&&!activePad())setInputMode(settings.touch?'TOUCH':'KEYBOARD');config()});window.addEventListener('resize',config);
function alignCar(car,u,lane=0){car.position.copy(at(u,lane));car.rotation.set(0,yaw(u),0);const v=curveSlope(u);car.userData.body.rotation.x=v}
function curveSlope(u){const a=at(u-.001),b=at(u+.001);return -Math.atan2(b.y-a.y,Math.hypot(b.x-a.x,b.z-a.z))}
function reset(){raceAccumulator=0;hudAccumulator=0;lastPlace=4;skidMarks.clear();t=.982;progress=-.018;speed=0;time=0;countdown=3.1;ai=[.986,.990,.994];aiSpeeds=[0,0,0];aiLanes=[-4.5,0,4.5];heading=yaw(t);velocityHeading=heading;totalScore=0;chainScore=0;flow=0;boostCharge=0;isBoosting=false;boostLatch=false;flooded=false;drafting=false;blackoutActive=false;mechanicCue='';combo=1;comboBonus=0;chainGrace=0;driftAngle=0;driftTime=0;driftMilestone=0;lastHit=0;zoneCooldown=0;riskCooldown=0;nearMissCooldown=0;shake=0;lastLap=0;lapStarted=0;laps=[];checkpoint=0;setpieceLap=-1;sector=districts[0].name;isDrifting=false;countersteering=false;offTrack=false;cleanTime=0;lastComboStep=0;ghostLap=[];ghostSampleAt=0;ghostIndex=0;ghost.visible=false;stats={bestChain:0,apex:0,contacts:0,wallKisses:0,nearMisses:0,perfectExits:0,boostsUsed:0};alignCar(player,t,2);rivals.forEach((r,i)=>alignCar(r,ai[i],aiLanes[i]));state='race';releaseAll();for(const id of ['menu','brief','settingsPanel','end'])show(id,false);show('hud',true);show('recenter',false);$('districtName').textContent=districts[0].name;$('districtHint').textContent=districts[0].hint;audioStart();config();toast(level.name+' · READY');camera.position.copy(player.position.clone().add(new THREE.Vector3(-Math.sin(heading)*11,5,-Math.cos(heading)*11)));updateHud();}
function title(){state='menu';for(const id of ['hud','controls','end','settingsPanel','brief','recenter'])show(id,false);show('menu',true);$('recordSummary').textContent=best||bestScore?`PERSONAL BEST / ${best?format(best):'--:--.-'} / ${bestScore.toLocaleString()} PTS`:'NO RECORD / FIRST RUN';releaseAll();}
$('start').onclick=()=>{state='brief';show('menu',false);show('brief',true);beep(180,.15);requestAnimationFrame(()=>$('briefTitle').focus())};$('deploy').onclick=reset;$('retry').onclick=reset;$('toTitle').onclick=title;$('quit').onclick=title;
function pause(){if(state==='settings')return;raceAccumulator=0;previous=state;state='settings';for(const id of ['end','menu','brief','controls','recenter'])show(id,false);show('settingsPanel',true);show('quit',previous==='race');$('resume').textContent=previous==='race'?'RESUME RACE':'BACK';releaseAll();requestAnimationFrame(()=>$('settingsTitle').focus())}
$('sound').onclick=()=>{if(music.started)soundEnabled=!soundEnabled;audioStart();music.setEnabled(soundEnabled);$('sound').textContent=soundEnabled?'SOUND ON':'SOUND OFF'};
$('settings').onclick=pause;$('pause').onclick=pause;$('resume').onclick=()=>{audioStart();state=previous;show('settingsPanel',false);if(state==='menu')show('menu',true);if(state==='brief')show('brief',true);if(state==='race'){show('hud',true);show('recenter',offTrack)}if(state==='end')show('end',true);config()};
function loseChain(message='CHAIN BROKEN'){stats.bestChain=Math.max(stats.bestChain,Math.round(chainScore));if(message.includes('LOST'))stats.contacts++;if(chainScore>=20)toast(message);chainScore=0;flow=0;combo=1;comboBonus=0;chainGrace=0;driftTime=0;driftMilestone=0;lastComboStep=0}
function bankChain(){stats.bestChain=Math.max(stats.bestChain,Math.round(chainScore));if(chainScore<10){chainScore=0;flow=0;combo=1;comboBonus=0;lastComboStep=0;return}const banked=Math.round(chainScore),charge=Math.round(boostFromBank(banked));totalScore+=banked;boostCharge=clamp(boostCharge+charge,0,BOOST_MAX);toast('BANKED +'+banked.toLocaleString()+' · BOOST +'+charge+'%');chainScore=0;flow=0;combo=1;comboBonus=0;lastComboStep=0}
function recenter(){if(state!=='race'||countdown>0)return;loseChain();player.position.copy(at(t));heading=yaw(t);velocityHeading=heading;speed=8;time+=2;shake=0;toast('BACK ON TRACK · +2 SEC')}$('recenter').onclick=recenter;
window.addEventListener('keydown',e=>{if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();setInputMode('KEYBOARD');keys[e.code]=true;if(e.code==='Escape'){if(state==='settings')$('resume').click();else if(state==='brief')title();else if(state==='race')pause()}if(e.code==='KeyR'&&!e.repeat)recenter();if(e.key==='Tab'&&(state==='settings'||state==='brief')){const panel=state==='settings'?$('settingsPanel'):$('brief'),items=[...panel.querySelectorAll('button,input,select,summary,a,[tabindex="0"]')].filter(el=>!el.disabled&&el.offsetParent!==null);if(items.length){const first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}}});window.addEventListener('keyup',e=>keys[e.code]=false);window.addEventListener('blur',()=>{if(state==='race')pause();else releaseAll()});document.addEventListener('visibilitychange',()=>{if(document.hidden){if(state==='race')pause();audio?.suspend()}});
for(const id of ['left','right','brake','boost','drift']){const b=$(id);b.onpointerdown=e=>{e.preventDefault();setInputMode('TOUCH');b.setPointerCapture(e.pointerId);held[id]=true;b.classList.add('held');audioStart()};const release=()=>{held[id]=false;b.classList.remove('held')};b.onpointerup=release;b.onpointercancel=release;b.onlostpointercapture=release}window.addEventListener('contextmenu',e=>e.preventDefault());
// A bounded particle pool for exhaust sparks, drifts, and wall contacts.
const particleCount=160,particlePos=new Float32Array(particleCount*3),particleColors=new Float32Array(particleCount*3),particles=Array.from({length:particleCount},()=>({life:0,v:new THREE.Vector3()}));particlePos.fill(-10000);const pg=new THREE.BufferGeometry();pg.setAttribute('position',new THREE.BufferAttribute(particlePos,3));pg.setAttribute('color',new THREE.BufferAttribute(particleColors,3));const pm=new THREE.PointsMaterial({size:.18,vertexColors:true,transparent:true,opacity:.9,depthWrite:false,blending:THREE.AdditiveBlending});const points=new THREE.Points(pg,pm);points.frustumCulled=false;scene.add(points);let particleIndex=0;
function emit(count,color){if(!settings.effects)return;const c=new THREE.Color(color);for(let k=0;k<count;k++){const i=particleIndex++%particleCount,p=particles[i];p.life=.35+Math.random()*.4;p.v.set((Math.random()-.5)*6,Math.random()*3,(Math.random()-.5)*6);particlePos[i*3]=player.position.x-Math.sin(heading)*2;particlePos[i*3+1]=player.position.y+.4;particlePos[i*3+2]=player.position.z-Math.cos(heading)*2;particleColors.set([c.r,c.g,c.b],i*3)}}
function particlesStep(dt){for(let i=0;i<particleCount;i++){const p=particles[i];if(p.life>0){p.life-=dt;particlePos[i*3]+=p.v.x*dt;particlePos[i*3+1]+=p.v.y*dt;particlePos[i*3+2]+=p.v.z*dt;if(p.life<=0)particlePos[i*3+1]=-10000}}pg.attributes.position.needsUpdate=true;pg.attributes.color.needsUpdate=true}
function format(s){return Math.floor(s/60).toString().padStart(2,'0')+':'+Math.floor(s%60).toString().padStart(2,'0')+'.'+Math.floor(s%1*10)}
function captureGhost(){if(!settings.ghosts)return;const lapClock=time-lapStarted;if(lapClock+.001<ghostSampleAt)return;ghostLap.push([Number(lapClock.toFixed(2)),Number(player.position.x.toFixed(2)),Number(player.position.y.toFixed(2)),Number(player.position.z.toFixed(2)),Number(heading.toFixed(3))]);ghostSampleAt+=.1}
function commitGhostLap(lapTime){const improved=settings.ghosts&&ghostLap.length>20&&lapTime<ghostRecord.time;if(improved){ghostRecord={time:lapTime,samples:ghostLap};try{localStorage.setItem(level.record+'-lap-ghost',JSON.stringify(ghostRecord))}catch{}}ghostLap=[];ghostSampleAt=0;ghostIndex=0;return improved}
function updateGhost(now,dt){const samples=ghostRecord.samples,clock=time-lapStarted;if(!settings.ghosts||countdown>0||samples.length<2){ghost.visible=false;return}while(ghostIndex<samples.length-2&&samples[ghostIndex+1][0]<clock)ghostIndex++;const a=samples[ghostIndex],b=samples[ghostIndex+1];if(!a||!b||clock>b[0]+.2){ghost.visible=false;return}const mix=clamp((clock-a[0])/Math.max(.01,b[0]-a[0]),0,1);ghost.visible=true;ghost.position.set(THREE.MathUtils.lerp(a[1],b[1],mix),THREE.MathUtils.lerp(a[2],b[2],mix)+.05,THREE.MathUtils.lerp(a[3],b[3],mix));ghost.rotation.set(0,a[4]+angle(b[4]-a[4])*mix,0);animateCar(ghost,Math.hypot(b[1]-a[1],b[3]-a[3])/Math.max(.01,b[0]-a[0]),false,now,dt)}
function coaching(){if(stats.contacts>3)return'Brake earlier for marked hazards; contact is breaking too many chains.';if(stats.apex<9)return'Enter more lit apex zones sideways to build multiplier faster.';if(stats.bestChain<level.rankBands[0]/3)return'Hold angle longer, then release cleanly to bank a larger chain.';if(!stats.perfectExits)return'Countersteer before releasing the drift control to earn perfect exits.';return'Your line is clean. Push wall proximity and longer links for the next rank.'}
function finish(){
  stats.bestChain=Math.max(stats.bestChain,Math.round(chainScore));
  if(chainScore>0){totalScore+=Math.round(chainScore);chainScore=0}
  const finalLap=time-lapStarted;commitGhostLap(finalLap);laps.push(finalLap);ghost.visible=false;state='end';show('controls',false);show('recenter',false);show('end',true);show('countdown',false);
  const place=1+ai.filter(v=>v-1>progress).length,[bRank,aRank,sRank]=level.rankBands,rank=totalScore>=sRank?'S':totalScore>=aRank?'A':totalScore>=bRank?'B':'C',license=earnedLicense(rank,place),oldLicense=readLicense(level);
  $('endTag').textContent=level.name+' / DRIFT CLASSIFIED';$('endTitle').textContent=license>oldLicense?'License upgraded: '+medalNames[license]+'.':rank==='S'?'The perfect breach.':place===1?'Circuit owned.':'Line complete.';
  const timeRecord=!best||time<best,scoreRecord=totalScore>bestScore;if(timeRecord){best=time;try{localStorage.setItem(level.record+'-time-best',String(best))}catch{}}if(scoreRecord){bestScore=totalScore;try{localStorage.setItem(level.record+'-drift-best',String(bestScore))}catch{}}if(license>oldLicense){try{localStorage.setItem(level.record+'-license',String(license))}catch{}renderLicenseBoard()}
  $('endText').textContent=`Position ${place} of 4 · Drift rank ${rank} · ${medalNames[license]} license. ${scoreRecord?'New drift record.':'Best drift score: '+bestScore.toLocaleString()+'.'} ${coaching()}`;
  const resultRows=[...laps.map((lap,i)=>['LAP '+(i+1),format(lap)]),['TOTAL TIME',format(time)],['DRIFT SCORE',totalScore.toLocaleString()],['DRIFT RANK',rank],['LICENSE',medalNames[license]],['BEST CHAIN',stats.bestChain.toLocaleString()],['APEX LINKS',stats.apex+' / 18'],['PERFECT EXITS',stats.perfectExits],['BOOST DEPLOYS',stats.boostsUsed],['NEAR MISSES',stats.nearMisses],['WALL KISSES',stats.wallKisses],['CONTACTS',stats.contacts]];
  $('results').innerHTML=resultRows.map(([label,value])=>`<div><span>${label}</span><strong>${value}</strong></div>`).join('');requestAnimationFrame(()=>$('endTitle').focus());beep(440,.4)
}
// Draw the map from actual circuit samples rather than a decorative outline.
const map=$('minimap'),ctx=map.getContext('2d'),mapBase=document.createElement('canvas');mapBase.width=map.width=180;mapBase.height=map.height=146;const mc=mapBase.getContext('2d'),xs=samples.map(p=>p.x),zs=samples.map(p=>p.z),mapBounds={minX:Math.min(...xs),maxX:Math.max(...xs),minZ:Math.min(...zs),maxZ:Math.max(...zs)};const mapPoint=p=>[14+(p.x-mapBounds.minX)/(mapBounds.maxX-mapBounds.minX)*152,12+(p.z-mapBounds.minZ)/(mapBounds.maxZ-mapBounds.minZ)*122];mc.lineWidth=7;mc.strokeStyle='#28364b';mc.beginPath();samples.forEach((p,i)=>{const [x,y]=mapPoint(p);i?mc.lineTo(x,y):mc.moveTo(x,y)});mc.closePath();mc.stroke();mc.lineWidth=1;mc.strokeStyle='#6ad4d3';mc.stroke();const [sx,sy]=mapPoint(at(0));mc.fillStyle='#fff';mc.fillRect(sx-3,sy-3,6,6);
for(const u of driftZones){const [x,y]=mapPoint(at(u));mc.fillStyle=level.accent2;mc.beginPath();mc.arc(x,y,2,0,Math.PI*2);mc.fill()}const mappedHazards=new Set();for(const body of collisionBodies){const key=Math.round(body.t*1000);if(mappedHazards.has(key))continue;mappedHazards.add(key);const [x,y]=mapPoint(at(body.t));mc.fillStyle='#ffb55f';mc.fillRect(x-1.5,y-1.5,3,3)}
function drawMap(){ctx.clearRect(0,0,180,146);ctx.drawImage(mapBase,0,0);[...ai,t].forEach((u,i)=>{const [x,y]=mapPoint(at(u));ctx.fillStyle=i===3?level.accent:colors[i];ctx.beginPath();ctx.arc(x,y,i===3?4:3,0,Math.PI*2);ctx.fill()})}
function updateHud(){const lap=Math.min(3,Math.floor(Math.max(0,progress))+1);$('cores').textContent=lap+' / 3';const place=1+ai.filter(v=>v-1>progress).length;if(place<lastPlace&&time>4)toast(place===1?'RACE LEADER':'OVERTAKE · P'+place);lastPlace=place;$('kills').textContent=place+' / 4';$('timer').textContent=format(time);$('dashStatus').textContent=Math.round(speed*3.6);$('currentLap').textContent=format(time-lapStarted);$('flowFill').style.width=flow+'%';$('boostFill').style.width=boostCharge+'%';$('boostValue').textContent=Math.round(boostCharge)+'%';$('combo').textContent='×'+combo.toFixed(1);$('chainScore').textContent=Math.round(chainScore).toLocaleString();$('totalScore').textContent=totalScore.toLocaleString();$('driftReadout').textContent=isBoosting?(blackoutActive?'OVERVOLT BOOST':'BOOST DEPLOYED'):isDrifting?Math.round(driftAngle*180/Math.PI)+'°  '+(countersteering?'COUNTERSTEER':'HOLD THE LINE'):chainGrace>0&&chainScore>0?'LINK '+chainGrace.toFixed(1)+'s':flooded?'HYDROPLANE · FEATHER THROTTLE':drafting?'CLOUD DRAFT · CHARGING':blackoutActive?'GRID BLACKOUT · BOOST AMPLIFIED':'';document.body.classList.toggle('drifting',isDrifting&&settings.effects&&!settings.reducedMotion);document.body.classList.toggle('boosting',isBoosting);document.body.classList.toggle('grid-blackout',blackoutActive);show('recenter',offTrack||speed<1&&time>4);drawMap()}
const aiProfiles=[{base:-4.6,bravery:.92,line:.8},{base:0,bravery:1,line:1.08},{base:4.6,bravery:1.06,line:.92}];
function signedLane(position,u){const center=at(u),h=yaw(u);return(position.x-center.x)*Math.cos(h)-(position.z-center.z)*Math.sin(h)}
function updateRivals(dt){const playerLane=signedLane(player.position,t);for(let i=0;i<3;i++){const profile=aiProfiles[i],rivalProgress=ai[i]-1,gap=progress-rivalProgress,bend=curvature(ai[i]+.014),turn=angle(yaw(ai[i]+.034)-yaw(ai[i]+.008));let targetLane=profile.base-turn*7*profile.line+Math.sin(ai[i]*12+i*2.1)*.45;const hazard=collisionBodies.find(body=>{const ahead=wrap(body.t-ai[i])*LENGTH;return ahead>3&&ahead<34&&Math.abs(body.lane-aiLanes[i])<body.radius+2.4});if(hazard)targetLane+=Math.sign(aiLanes[i]-hazard.lane||i-1||1)*(hazard.radius+3.2);if(Math.abs(gap)*LENGTH<34)targetLane+=Math.sign(aiLanes[i]-playerLane||i-1||1)*2.8;for(let j=0;j<3;j++){if(i===j)continue;const rivalGap=Math.abs((ai[i]-ai[j])*LENGTH);if(rivalGap<15&&Math.abs(aiLanes[i]-aiLanes[j])<3.4)targetLane+=Math.sign(aiLanes[i]-aiLanes[j]||i-j)*2.2}targetLane=clamp(targetLane,-8.4,8.4);aiLanes[i]=THREE.MathUtils.lerp(aiLanes[i],targetLane,1-Math.exp(-dt*1.7));const basePace=(settings.difficulty==='expert'?54:settings.difficulty==='normal'?48:38)*level.pace,catchup=clamp(gap*LENGTH*.024,-2.8,3.2),target=(basePace+i*1.35-Math.min(19,bend*40)+catchup)*profile.bravery;aiSpeeds[i]+=(target-aiSpeeds[i])*(1-Math.exp(-dt*1.4));ai[i]+=aiSpeeds[i]*dt/LENGTH;alignCar(rivals[i],ai[i],aiLanes[i]);const aiTurn=angle(yaw(ai[i]+.008)-yaw(ai[i]-.008));rivals[i].rotation.y+=aiTurn*.16;rivals[i].userData.body.rotation.z=THREE.MathUtils.lerp(rivals[i].userData.body.rotation.z,-aiTurn*.28,dt*7);const dx=player.position.x-rivals[i].position.x,dz=player.position.z-rivals[i].position.z,d=Math.hypot(dx,dz);if(d<2.8){const nx=d>.001?dx/d:1,nz=d>.001?dz/d:0,push=(2.8-d)*.55;player.position.x+=nx*push;player.position.z+=nz*push;aiLanes[i]=clamp(aiLanes[i]-Math.sign(signedLane(player.position,t)-aiLanes[i]||1)*.45,-8.4,8.4);if(lastHit<=0){speed*=.68;velocityHeading+=angle(Math.atan2(nx,nz)-velocityHeading)*.24;lastHit=.5;shake=.2;impact();emit(settings.reducedMotion?3:10,0xffbd68);beep(95,.08);juice('impact');rumble(.5,100);loseChain('CONTACT · CHAIN LOST')}}else if(d<4.6&&speed>28&&isDrifting&&nearMissCooldown<=0){const award=Math.round(180*combo);chainScore+=award;flow=clamp(flow+8,0,100);stats.nearMisses++;nearMissCooldown=1.4;toast('THREAD THE NEEDLE +'+award);beep(760,.09);rumble(.18,55)}}}
function updateRace(dt){if(countdown>0){const old=Math.ceil(countdown);countdown-=dt;if(Math.ceil(countdown)!==old){toast(countdown>0?String(Math.ceil(countdown)):'GO!');beep(countdown>0?220:520,.15)}return}
time+=dt;lastHit-=dt;zoneCooldown-=dt;riskCooldown-=dt;nearMissCooldown-=dt;const localT=wrap(t);flooded=level.mechanic==='flood'&&(localT>.25&&localT<.34||localT>.64&&localT<.73);blackoutActive=level.mechanic==='blackout'&&Math.floor(time/9)%2===1;drafting=level.mechanic==='draft'&&player.position.y>34&&!offTrack&&!isDrifting&&speed>32;if(drafting)boostCharge=clamp(boostCharge+dt*4.5,0,BOOST_MAX);const cue=flooded?'FLOOD WATER':drafting?'CLOUD DRAFT':blackoutActive?'GRID BLACKOUT':'';if(cue&&cue!==mechanicCue){toast(cue+(drafting?' · BOOST CHARGING':blackoutActive?' · OVERVOLT READY':' · GRIP REDUCED'));beep(blackoutActive?180:620,.1)}mechanicCue=cue;const controls=readControls(),{steer,throttle,brake,handbrake,boost:boostButton,drift:driftButton}=controls,braking=brake>.02;isBoosting=!!(boostButton&&boostCharge>.1&&speed>10&&countdown<=0);if(isBoosting&&!boostLatch){stats.boostsUsed++;toast(blackoutActive?'OVERVOLT BOOST':'BOOST DEPLOYED');beep(blackoutActive?1080:930,.08);rumble(.24,70)}boostLatch=isBoosting;if(isBoosting)boostCharge=spendBoost(boostCharge,dt*(blackoutActive?.68:1));
visualSteer=steer;brakeActive=braking||handbrake;const driftNow=!!(driftButton&&Math.abs(steer)>.12&&speed>16),wasDrifting=isDrifting,enteringDrift=driftNow&&!wasDrifting,exitingDrift=!driftNow&&wasDrifting,exitDuration=driftTime;isDrifting=driftNow;if(enteringDrift){velocityHeading-=steer*(handbrake?.13:.075)*(1.08+(1-level.grip));rumble(.16,55)}const surfaceGrip=level.grip*(flooded?.68:1),steeringGrip=(isDrifting?2.15:10)*surfaceGrip,boostPower=blackoutActive?54:40,boostTop=blackoutActive?18:13,top=level.topSpeed+(isBoosting?boostTop:0),coast=throttle>.02?0:10;speed+=(throttle*27+(isBoosting?boostPower:0)-coast-brake*44-(handbrake?12:0)-speed*(isDrifting?.13:.19))*dt;speed=clamp(speed,0,top);const steerRate=(1.72-Math.min(speed,80)*.009)*(isDrifting?1.62:1)*(1.06+(1-surfaceGrip)*.25);heading+=steer*steerRate*dt*Math.min(speed/8,1);velocityHeading+=angle(heading-velocityHeading)*(1-Math.exp(-steeringGrip*dt));const signedSlip=angle(heading-velocityHeading);driftAngle=Math.abs(signedSlip);countersteering=isDrifting&&driftAngle>.12&&steer*signedSlip<-.025;player.position.x+=Math.sin(velocityHeading)*speed*dt;player.position.z+=Math.cos(velocityHeading)*speed*dt;
if(isDrifting&&driftAngle>.075){driftTime+=dt;chainGrace=1.25;flow=clamp(flow+(7+driftAngle*32+(countersteering?3:0))*dt,0,100);combo=clamp(1+Math.floor(flow/20)*.35+comboBonus,1,5);chainScore+=speed*driftAngle*13*combo*(countersteering?1.12:1)*dt;emit(settings.reducedMotion?0:2,driftAngle>.32?level.edgeA:level.edgeB);const step=Math.floor(combo*2);if(step>lastComboStep&&combo>=2){lastComboStep=step;toast('FLOW ×'+combo.toFixed(1));beep(420+step*35,.08)}const milestone=driftTime>=5?2:driftTime>=2.5?1:0;if(milestone>driftMilestone){driftMilestone=milestone;const award=milestone*250;chainScore+=award;flow=clamp(flow+10,0,100);toast(milestone===2?'DEEP DRIFT +500':'DRIFT LOCK +250');juice('apex-flash');beep(milestone===2?720:610,.1)}}else{if(exitingDrift&&exitDuration>=2.5&&driftAngle<.18){chainScore+=200;flow=clamp(flow+8,0,100);stats.perfectExits++;toast('PERFECT EXIT +200');beep(820,.1);rumble(.16,55)}if(chainGrace>0){chainGrace-=dt;if(chainGrace<=0)bankChain()}driftTime=0;driftMilestone=0;countersteering=false}
const near=nearest(player.position,t),wallLimit=TRACK_HALF_WIDTH-1.65;offTrack=near.d>TRACK_HALF_WIDTH-3.8;if(near.d>wallLimit){const p=at(near.t),dx=player.position.x-p.x,dz=player.position.z-p.z,d=Math.hypot(dx,dz);player.position.x=p.x+dx/d*wallLimit;player.position.z=p.z+dz/d*wallLimit;speed*=Math.exp(-1.8*dt);const roadHeading=yaw(near.t);if(Math.abs(angle(roadHeading-heading))<1.7){heading+=angle(roadHeading-heading)*dt*2;velocityHeading=heading}if(lastHit<=0){impact();beep(60,.1);emit(settings.reducedMotion?4:14,0xffaa44);shake=.25;lastHit=.35;juice('impact');rumble(.7,140);loseChain('WALL HIT · CHAIN LOST')}cleanTime=0}else cleanTime+=dt;
if(isDrifting&&near.d>TRACK_HALF_WIDTH-4.5&&near.d<wallLimit-.3&&riskCooldown<=0){const award=Math.round(90*combo);chainScore+=award;flow=clamp(flow+5,0,100);riskCooldown=1;stats.wallKisses++;toast('WALL KISS +'+award);emit(settings.reducedMotion?0:5,level.edgeA)}
for(const body of collisionBodies){const dx=player.position.x-body.x,dz=player.position.z-body.z,min=body.radius+1.25,d=Math.hypot(dx,dz);if(d<min){const nx=d>.001?dx/d:1,nz=d>.001?dz/d:0,push=min-d+.08;player.position.x+=nx*push;player.position.z+=nz*push;const away=Math.atan2(nx,nz);velocityHeading+=angle(away-velocityHeading)*.42;heading+=angle(away-heading)*.18;speed*=.48;if(lastHit<=0){lastHit=.55;shake=.32;impact();beep(72,.12);emit(settings.reducedMotion?5:18,0xffb05f);juice('impact');rumble(.85,180);loseChain(body.label+' · CHAIN LOST')}}}
progress+=advance(t,near.t);t=near.t;player.position.y=at(t).y;player.rotation.y=heading;player.userData.body.rotation.x=THREE.MathUtils.lerp(player.userData.body.rotation.x,curveSlope(t),dt*9);player.userData.body.rotation.z=THREE.MathUtils.lerp(player.userData.body.rotation.z,-steer*speed*.0018,dt*8);
const nextCP=Math.floor(Math.max(0,progress)*4);if(nextCP>checkpoint){checkpoint=nextCP;if(checkpoint%4!==0)toast('CHECKPOINT '+(checkpoint%4)+' / 3')}
if(Math.floor(progress)>lastLap&&progress<3){const completed=time-lapStarted;laps.push(completed);const ghostSaved=commitGhostLap(completed);lapStarted=time;lastLap=Math.floor(progress);toast('LAP '+(lastLap+1)+' / 3 · '+format(completed)+(ghostSaved?' · GHOST SAVED':''));beep(520,.18)}
const dist=district(Math.max(0,progress));if(sector!==dist.name){const clean=cleanTime>8;sector=dist.name;$('districtName').textContent=sector;$('districtHint').textContent=dist.hint;if(clean){totalScore+=300;toast('CLEAN SECTOR +300');beep(580,.1)}cleanTime=0}
const lapPhase=wrap(progress),lapIndex=Math.floor(Math.max(0,progress));if(lapPhase>.63&&lapPhase<.69&&setpieceLap<lapIndex){setpieceLap=lapIndex;toast(level.setpieceCue);juice('apex-flash');rumble(.2,75);beep(360,.14)}
const bend=curvature(t+.018),hazard=collisionBodies.find(body=>{const ahead=wrap(body.t-t)*LENGTH;return ahead>5&&ahead<42});$('corner').textContent=Math.abs(angle(yaw(t)-heading))>2?'WRONG WAY':hazard?hazard.label+' AHEAD':bend>.43?'HAIRPIN · BRAKE':bend>.20?'CORNER AHEAD':'';
for(const u of driftZones){if(circularDistance(u,t)*LENGTH<5&&near.d<5&&zoneCooldown<=0){zoneCooldown=2;if(isDrifting&&driftAngle>.12){const award=Math.round(250*combo);chainScore+=award;flow=clamp(flow+24,0,100);comboBonus=clamp(comboBonus+.5,0,2);stats.apex++;toast('APEX LINK +'+award);juice('apex-flash');rumble(.28,70);beep(650,.15)}else toast('APEX ZONE · ENTER SIDEWAYS')}}
updateRivals(dt);
captureGhost();skidMarks.update(player.position,heading,isDrifting&&settings.effects);if(progress>=3)finish()}
function animateCar(car,s,sliding,now,dt){for(const wheel of car.userData.wheels)wheel.rotateY(s*dt*1.8);for(const pivot of car.userData.wheelPivots){if(pivot.userData.front)pivot.rotation.y=THREE.MathUtils.lerp(pivot.rotation.y,car===player?visualSteer*.34:0,dt*9)}car.userData.brakeMaterial.emissiveIntensity=car===player&&brakeActive?4:1.3;if(car===player){const slip=angle(heading-velocityHeading);car.userData.body.rotation.y=THREE.MathUtils.lerp(car.userData.body.rotation.y,sliding?-slip*.12:0,dt*7);car.userData.body.position.y=THREE.MathUtils.lerp(car.userData.body.position.y,brakeActive?-.07:Math.sin(now*.012)*.018,dt*8)}for(const flame of car.userData.flames){const active=sliding||car===player&&isBoosting;flame.visible=active&&!settings.reducedMotion;flame.material.color.setHex(car===player&&isBoosting?0xffd27a:0x76ffff);flame.scale.y=active?(car===player&&isBoosting?1.55:.55)+Math.sin(now*.08)*.12:0}}
function frame(now){requestAnimationFrame(frame);const rawDelta=Math.max(0,Math.min((now-last)/1000,.12)),dt=Math.min(rawDelta,.05);last=now;pollGamepadActions();qualityTime+=rawDelta;qualityFrames++;if(settings.quality==='auto'&&autoQuality==='high'&&qualityTime>5){if(qualityFrames/qualityTime<42){autoQuality='low';config();toast('ADAPTIVE GRAPHICS · BATTERY MODE')}qualityTime=0;qualityFrames=0}let viewTrack=t;updateStartLights(countdown,state==='race');if(state==='race'){raceAccumulator+=rawDelta;while(raceAccumulator>=1/60&&state==='race'){updateRace(1/60);raceAccumulator-=1/60}hudAccumulator+=rawDelta;if(hudAccumulator>=.05){updateHud();hudAccumulator=0}show('countdown',countdown>0||time<.65);$('countdown').textContent=countdown>0?String(Math.min(3,Math.ceil(countdown))):'GO';toastTime-=rawDelta;if(toastTime<=0)show('toast',false);particlesStep(rawDelta);animateCar(player,speed,isDrifting,now,dt);rivals.forEach((r,i)=>animateCar(r,aiSpeeds[i],curvature(ai[i])>.2,now,dt));updateGhost(now,dt)}
if(soundTestUntil&&now>=soundTestUntil){soundTestUntil=0;$('soundTestStatus').textContent='Ready. Choose a channel.'}const normalMusic=state==='race'||state==='settings'&&previous==='race'?'race':'intro';music.setPhase(soundTestUntil?soundTestTrack:normalMusic,state==='settings'&&!soundTestUntil);music.setIntensity(state==='race'?Math.max(flow/100,speed/level.topSpeed*.28,isBoosting?.92:0):0);if(engine){engine.frequency.setTargetAtTime(42+speed*2.2+(isBoosting?55:0),audio.currentTime,.08);engineGain.gain.setTargetAtTime(state==='race'&&soundEnabled?settings.volume/100*(.025+speed*.0003+(isBoosting?.018:0)):0,audio.currentTime,.08);motor.frequency.setTargetAtTime(120+speed*(isDrifting?7:5)+(isBoosting?110:0),audio.currentTime,.06);motorGain.gain.setTargetAtTime(state==='race'&&soundEnabled?settings.volume/100*(isBoosting?.026:.015):0,audio.currentTime,.08);tyreFilter?.frequency.setTargetAtTime((level.id==='cryoline'?2350:level.id==='solara'?1150:1650)+driftAngle*900,audio.currentTime,.08);tyreGain?.gain.setTargetAtTime(state==='race'&&isDrifting&&soundEnabled?settings.volume/100*(level.id==='solara'?.045:.055):0,audio.currentTime,.06)}
if(state==='race'||state==='settings'&&previous==='race'||state==='end'){const forward=new THREE.Vector3(Math.sin(heading),0,Math.cos(heading)),right=new THREE.Vector3(Math.cos(heading),0,-Math.sin(heading)),slip=angle(heading-velocityHeading);const desired=player.position.clone().addScaledVector(forward,-11).addScaledVector(right,isDrifting?slip*2.2:0);desired.y+=5.3;if(state==='race'&&countdown>1.3){desired.add(new THREE.Vector3(Math.cos(heading)*3.8,-1.4,-Math.sin(heading)*3.8))}camera.position.lerp(desired,1-Math.exp(-7*dt));const look=player.position.clone().addScaledVector(forward,state==='race'&&countdown>1.3?5:15);look.y+=1.4;shake=Math.max(0,shake-dt);if(settings.effects&&!settings.reducedMotion&&shake>0){camera.position.x+=Math.sin(now*.15)*shake*.35;camera.position.y+=Math.cos(now*.11)*shake*.25}camera.lookAt(look);if(isDrifting&&!settings.reducedMotion)camera.rotateZ(slip*-.12);const targetFov=64+speed/level.topSpeed*3+(isDrifting&&!settings.reducedMotion?3:0);camera.fov=THREE.MathUtils.lerp(camera.fov,targetFov,dt*4);camera.updateProjectionMatrix()}else{const u=wrap(now*.000012+.05),p=at(u),h=yaw(u);viewTrack=u;camera.position.set(p.x-Math.sin(h)*17,p.y+7,p.z-Math.cos(h)*17);camera.lookAt(at(u+.025));alignCar(player,u,2);rivals.forEach((r,i)=>alignCar(r,u+.01+i*.007,(i-1)*5));animateCar(player,20,false,now,dt)}
ambientCars.forEach((g,i)=>{g.position.set(290+i*12,48+i*9,((now*.022+i*110)%850)-420)});updateWorldSetpieces(now);const quality=effectiveQuality(),effectsOn=settings.effects&&!settings.reducedMotion,midnightCover=level.id==='midnight'&&(viewTrack>.315&&viewTrack<.435||viewTrack>.465&&viewTrack<.627);atmosphere.update(camera,now,effectsOn&&!midnightCover,quality,speed/level.topSpeed);postFX.render(scene,camera,quality==='high'&&effectsOn,isDrifting,now)}
config();alignCar(player,t,2);requestAnimationFrame(frame);
