import * as THREE from './three.module.js';
import {at,yaw,angle,curvature,nearest,advance,wrap,LENGTH,samples,district,driftZones,circularDistance} from './track.js';
import {scene,makeCar,ambientCars,updateStartLights} from './world.js';
import {createPostFX,createAtmosphere,createSkidMarks} from './effects.js';
import {MusicDirector} from './music.js';
const $=id=>document.getElementById(id),clamp=THREE.MathUtils.clamp;
let settings={volume:35,musicVolume:38,quality:'auto',difficulty:'casual',effects:true,touch:matchMedia('(pointer:coarse)').matches,reducedMotion:matchMedia('(prefers-reduced-motion:reduce)').matches};try{Object.assign(settings,JSON.parse(localStorage.getItem('neon-race-settings')||'{}'))}catch{}
for(const k in settings)$(k)[typeof settings[k]==='boolean'?'checked':'value']=settings[k];
let renderer;try{renderer=new THREE.WebGLRenderer({canvas:$('world'),antialias:true,powerPreference:'high-performance'})}catch{$('error').classList.remove('hidden');throw Error('WebGL unavailable')}
renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.2;
const camera=new THREE.PerspectiveCamera(64,innerWidth/innerHeight,.1,1500),player=makeCar(0x56e3d3),rivals=[makeCar(0xef4b87,27),makeCar(0xffbc5b,4),makeCar(0x9b8cff,88)],colors=['#ff548e','#ffc265','#a58cff'];
// Real headlamps follow the car's pitch without costly shadow maps.
for(const x of [-.7,.7]){const headlamp=new THREE.SpotLight(0x9beaff,420,38,.34,.75,1.5);headlamp.position.set(x,.78,2.7);headlamp.target.position.set(x,-.2,22);player.userData.body.add(headlamp,headlamp.target)}
const postFX=createPostFX(renderer),atmosphere=createAtmosphere(scene),skidMarks=createSkidMarks(scene);
let state='menu',previous='menu',t=.982,progress=-.018,speed=0,heading=0,velocityHeading=0,time=0,countdown=3.1,toastTime=0,lastHit=0,best=null,bestScore=0,totalScore=0,chainScore=0,flow=0,combo=1,comboBonus=0,chainGrace=0,driftAngle=0,driftTime=0,isDrifting=false,zoneCooldown=0,shake=0,lastLap=0,lapStarted=0,laps=[],sector='',checkpoint=0,cleanTime=0;
const music=new MusicDirector(status=>{if(status==='unavailable')$('audioStatus').textContent='Music unavailable. Driving is still available.';else $('audioStatus').textContent=status==='loading'?'Loading soundtrack…':'Soundtrack by Tomasz Kucza'});music.setVolume(settings.musicVolume);let soundEnabled=true;
let brakeActive=false,lastPlace=4,visualSteer=0,autoQuality=matchMedia('(pointer:coarse)').matches?'low':'high',hudAccumulator=0,qualityTime=0,qualityFrames=0;
let ai=[.986,.990,.994],aiSpeeds=[0,0,0],keys={},held={},audio,engine,engineGain,motor,motorGain,tyre,tyreGain,noiseBuffer;let last=performance.now(),raceAccumulator=0;
try{best=Number(localStorage.getItem('neon-midnight-v2-best'))||null}catch{}
try{bestScore=Number(localStorage.getItem('neon-midnight-drift-best'))||0}catch{}
function audioStart(){try{audio??=new AudioContext();audio.resume();music.unlock(audio);$('sound').textContent=soundEnabled?'SOUND ON':'SOUND OFF';if(!engine){engine=audio.createOscillator();engineGain=audio.createGain();engine.type='sawtooth';engineGain.gain.value=0;const filter=audio.createBiquadFilter();filter.type='lowpass';filter.frequency.value=650;engine.connect(filter).connect(engineGain).connect(audio.destination);engine.start();motor=audio.createOscillator();motorGain=audio.createGain();motor.type='sine';motorGain.gain.value=0;motor.connect(motorGain).connect(audio.destination);motor.start();noiseBuffer=audio.createBuffer(1,audio.sampleRate,audio.sampleRate);const data=noiseBuffer.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=Math.random()*2-1;tyre=audio.createBufferSource();tyre.buffer=noiseBuffer;tyre.loop=true;const tyreFilter=audio.createBiquadFilter();tyreFilter.type='bandpass';tyreFilter.frequency.value=1800;tyreFilter.Q.value=3;tyreGain=audio.createGain();tyreGain.gain.value=0;tyre.connect(tyreFilter).connect(tyreGain).connect(audio.destination);tyre.start()}}catch{}}
function beep(freq=220,duration=.1){audioStart();if(!settings.volume||!soundEnabled)return;if(!audio)return;const o=audio.createOscillator(),g=audio.createGain();o.type='triangle';o.frequency.value=freq;g.gain.setValueAtTime(settings.volume/100*.12,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+duration)}
function impact(){if(!audio||!noiseBuffer||!settings.volume||!soundEnabled)return;const n=audio.createBufferSource(),g=audio.createGain();n.buffer=noiseBuffer;g.gain.setValueAtTime(settings.volume/100*.22,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.18);n.connect(g).connect(audio.destination);n.start();n.stop(audio.currentTime+.2)}
function show(id,on){$(id).classList.toggle('hidden',!on)}function toast(s){$('toast').textContent=s;toastTime=2.5;show('toast',true)}
function releaseAll(){keys={};held={};for(const id of ['left','right','brake','drift'])$(id).classList.remove('held')}
function effectiveQuality(){return settings.quality==='auto'?autoQuality:settings.quality}
function config(){const quality=effectiveQuality(),ratio=Math.min(devicePixelRatio,quality==='high'?1.6:1);music.setVolume(settings.musicVolume);renderer.setPixelRatio(ratio);renderer.setSize(innerWidth,innerHeight);postFX.resize(innerWidth*ratio,innerHeight*ratio);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();document.body.classList.toggle('no-effects',!settings.effects||settings.reducedMotion);document.body.classList.toggle('reduced-motion',settings.reducedMotion);document.body.classList.toggle('touch-mode',settings.touch);show('controls',settings.touch&&state==='race')}
for(const k in settings)$(k).addEventListener('change',()=>{settings[k]=typeof settings[k]==='boolean'?$(k).checked:$(k).value;try{localStorage.setItem('neon-race-settings',JSON.stringify(settings))}catch{}config()});window.addEventListener('resize',config);
function alignCar(car,u,lane=0){car.position.copy(at(u,lane));car.rotation.set(0,yaw(u),0);const v=curveSlope(u);car.userData.body.rotation.x=v}
function curveSlope(u){const a=at(u-.001),b=at(u+.001);return -Math.atan2(b.y-a.y,Math.hypot(b.x-a.x,b.z-a.z))}
function reset(){raceAccumulator=0;hudAccumulator=0;lastPlace=4;skidMarks.clear();t=.982;progress=-.018;speed=0;time=0;countdown=3.1;ai=[.986,.990,.994];aiSpeeds=[0,0,0];heading=yaw(t);velocityHeading=heading;totalScore=0;chainScore=0;flow=0;combo=1;comboBonus=0;chainGrace=0;driftAngle=0;driftTime=0;lastHit=0;zoneCooldown=0;shake=0;lastLap=0;lapStarted=0;laps=[];checkpoint=0;sector='01 / NEON MARKET';isDrifting=false;cleanTime=0;alignCar(player,t,2);rivals.forEach((r,i)=>alignCar(r,ai[i],(i-1)*5));state='race';releaseAll();for(const id of ['menu','brief','settingsPanel','end'])show(id,false);show('hud',true);show('recenter',true);$('districtName').textContent='01 / NEON MARKET';$('districtHint').textContent='Open straight · build speed';audioStart();config();toast('3');camera.position.copy(player.position.clone().add(new THREE.Vector3(-Math.sin(heading)*11,5,-Math.cos(heading)*11)));updateHud();}
function title(){state='menu';for(const id of ['hud','controls','end','settingsPanel','brief','recenter'])show(id,false);show('menu',true);releaseAll();}
$('start').onclick=()=>{state='brief';show('menu',false);show('brief',true);beep(180,.15);requestAnimationFrame(()=>$('briefTitle').focus())};$('deploy').onclick=reset;$('retry').onclick=reset;$('toTitle').onclick=title;$('quit').onclick=title;
function pause(){if(state==='settings')return;raceAccumulator=0;previous=state;state='settings';for(const id of ['end','menu','brief','controls','recenter'])show(id,false);show('settingsPanel',true);show('quit',previous==='race');$('resume').textContent=previous==='race'?'RESUME RACE':'BACK';releaseAll();requestAnimationFrame(()=>$('settingsTitle').focus())}
$('sound').onclick=()=>{if(music.started)soundEnabled=!soundEnabled;audioStart();music.setEnabled(soundEnabled);$('sound').textContent=soundEnabled?'SOUND ON':'SOUND OFF'};
$('settings').onclick=pause;$('pause').onclick=pause;$('resume').onclick=()=>{audioStart();state=previous;show('settingsPanel',false);if(state==='menu')show('menu',true);if(state==='brief')show('brief',true);if(state==='race'){show('hud',true);show('recenter',true)}if(state==='end')show('end',true);config()};
function loseChain(message='CHAIN BROKEN'){if(chainScore>=20)toast(message);chainScore=0;flow=0;combo=1;comboBonus=0;chainGrace=0;driftTime=0}
function bankChain(){if(chainScore<10){chainScore=0;flow=0;combo=1;comboBonus=0;return}const banked=Math.round(chainScore);totalScore+=banked;toast('BANKED +'+banked.toLocaleString());chainScore=0;flow=0;combo=1;comboBonus=0}
function recenter(){if(state!=='race'||countdown>0)return;loseChain();player.position.copy(at(t));heading=yaw(t);velocityHeading=heading;speed=8;time+=2;shake=0;toast('BACK ON TRACK · +2 SEC')}$('recenter').onclick=recenter;
window.addEventListener('keydown',e=>{if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();keys[e.code]=true;if(e.code==='Escape'){if(state==='settings')$('resume').click();else if(state==='brief')title();else if(state==='race')pause()}if(e.code==='KeyR'&&!e.repeat)recenter();if(e.key==='Tab'&&(state==='settings'||state==='brief')){const panel=state==='settings'?$('settingsPanel'):$('brief'),items=[...panel.querySelectorAll('button,input,select,summary,a,[tabindex="0"]')].filter(el=>!el.disabled&&el.offsetParent!==null);if(items.length){const first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}}});window.addEventListener('keyup',e=>keys[e.code]=false);window.addEventListener('blur',()=>{if(state==='race')pause();else releaseAll()});document.addEventListener('visibilitychange',()=>{if(document.hidden){if(state==='race')pause();audio?.suspend()}});
for(const id of ['left','right','brake','drift']){const b=$(id);b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);held[id]=true;b.classList.add('held');audioStart()};const release=()=>{held[id]=false;b.classList.remove('held')};b.onpointerup=release;b.onpointercancel=release;b.onlostpointercapture=release}window.addEventListener('contextmenu',e=>e.preventDefault());
// A bounded particle pool for exhaust sparks, drifts, and wall contacts.
const particleCount=160,particlePos=new Float32Array(particleCount*3),particleColors=new Float32Array(particleCount*3),particles=Array.from({length:particleCount},()=>({life:0,v:new THREE.Vector3()}));particlePos.fill(-10000);const pg=new THREE.BufferGeometry();pg.setAttribute('position',new THREE.BufferAttribute(particlePos,3));pg.setAttribute('color',new THREE.BufferAttribute(particleColors,3));const pm=new THREE.PointsMaterial({size:.18,vertexColors:true,transparent:true,opacity:.9,depthWrite:false,blending:THREE.AdditiveBlending});const points=new THREE.Points(pg,pm);points.frustumCulled=false;scene.add(points);let particleIndex=0;
function emit(count,color){if(!settings.effects)return;const c=new THREE.Color(color);for(let k=0;k<count;k++){const i=particleIndex++%particleCount,p=particles[i];p.life=.35+Math.random()*.4;p.v.set((Math.random()-.5)*6,Math.random()*3,(Math.random()-.5)*6);particlePos[i*3]=player.position.x-Math.sin(heading)*2;particlePos[i*3+1]=player.position.y+.4;particlePos[i*3+2]=player.position.z-Math.cos(heading)*2;particleColors.set([c.r,c.g,c.b],i*3)}}
function particlesStep(dt){for(let i=0;i<particleCount;i++){const p=particles[i];if(p.life>0){p.life-=dt;particlePos[i*3]+=p.v.x*dt;particlePos[i*3+1]+=p.v.y*dt;particlePos[i*3+2]+=p.v.z*dt;if(p.life<=0)particlePos[i*3+1]=-10000}}pg.attributes.position.needsUpdate=true;pg.attributes.color.needsUpdate=true}
function format(s){return Math.floor(s/60).toString().padStart(2,'0')+':'+Math.floor(s%60).toString().padStart(2,'0')+'.'+Math.floor(s%1*10)}
function finish(){if(chainScore>0){totalScore+=Math.round(chainScore);chainScore=0}laps.push(time-lapStarted);state='end';show('controls',false);show('recenter',false);show('end',true);show('countdown',false);const place=1+ai.filter(v=>v-1>progress).length,rank=totalScore>=18000?'S':totalScore>=12000?'A':totalScore>=7000?'B':'C';$('endTag').textContent='MIDNIGHT CIRCUIT / DRIFT CLASSIFIED';$('endTitle').textContent=rank==='S'?'The perfect breach.':place===1?'You own the night.':'Line complete.';const timeRecord=!best||time<best,scoreRecord=totalScore>bestScore;if(timeRecord){best=time;try{localStorage.setItem('neon-midnight-v2-best',String(best))}catch{}}if(scoreRecord){bestScore=totalScore;try{localStorage.setItem('neon-midnight-drift-best',String(bestScore))}catch{}}$('endText').textContent=`Position ${place} of 4 · Drift rank ${rank}. ${scoreRecord?'New drift record.':'Best drift score: '+bestScore.toLocaleString()+'.'}`;$('results').innerHTML=laps.map((l,i)=>`<div><span>LAP ${i+1}</span><strong>${format(l)}</strong></div>`).join('')+`<div><span>TOTAL TIME</span><strong>${format(time)}</strong></div><div><span>DRIFT SCORE</span><strong>${totalScore.toLocaleString()}</strong></div><div><span>DRIFT RANK</span><strong>${rank}</strong></div>`;requestAnimationFrame(()=>$('endTitle').focus());beep(440,.4)}
// Draw the map from actual circuit samples rather than a decorative outline.
const map=$('minimap'),ctx=map.getContext('2d'),mapBase=document.createElement('canvas');mapBase.width=map.width=180;mapBase.height=map.height=146;const mc=mapBase.getContext('2d');const mapPoint=p=>[14+(p.x+240)/510*152,12+(p.z+220)/440*122];mc.lineWidth=7;mc.strokeStyle='#28364b';mc.beginPath();samples.forEach((p,i)=>{const [x,y]=mapPoint(p);i?mc.lineTo(x,y):mc.moveTo(x,y)});mc.closePath();mc.stroke();mc.lineWidth=1;mc.strokeStyle='#6ad4d3';mc.stroke();const [sx,sy]=mapPoint(at(0));mc.fillStyle='#fff';mc.fillRect(sx-3,sy-3,6,6);
function drawMap(){ctx.clearRect(0,0,180,146);ctx.drawImage(mapBase,0,0);[...ai,t].forEach((u,i)=>{const [x,y]=mapPoint(at(u));ctx.fillStyle=i===3?'#a1fff2':colors[i];ctx.beginPath();ctx.arc(x,y,i===3?4:3,0,Math.PI*2);ctx.fill()})}
function updateHud(){const lap=Math.min(3,Math.floor(Math.max(0,progress))+1);$('cores').textContent=lap+' / 3';const place=1+ai.filter(v=>v-1>progress).length;if(place<lastPlace&&time>4)toast(place===1?'RACE LEADER':'OVERTAKE · P'+place);lastPlace=place;$('kills').textContent=place+' / 4';$('timer').textContent=format(time);$('dashStatus').textContent=Math.round(speed*3.6);$('currentLap').textContent=format(time-lapStarted);$('flowFill').style.width=flow+'%';$('combo').textContent='×'+combo.toFixed(1);$('chainScore').textContent=Math.round(chainScore).toLocaleString();$('totalScore').textContent=totalScore.toLocaleString();$('driftReadout').textContent=isDrifting?Math.round(driftAngle*180/Math.PI)+'°  HOLD THE LINE':chainGrace>0&&chainScore>0?'LINK '+chainGrace.toFixed(1)+'s':'';document.body.classList.toggle('drifting',isDrifting&&settings.effects&&!settings.reducedMotion);drawMap()}
function updateRace(dt){if(countdown>0){const old=Math.ceil(countdown);countdown-=dt;if(Math.ceil(countdown)!==old){toast(countdown>0?String(Math.ceil(countdown)):'GO!');beep(countdown>0?220:520,.15)}return}
time+=dt;lastHit-=dt;zoneCooldown-=dt;const pad=navigator.getGamepads?.()[0],padSteer=Math.abs(pad?.axes?.[0]||0)>.12?-(pad.axes[0]):0,padGas=(pad?.buttons?.[7]?.value||0)>.12,padBrake=(pad?.buttons?.[6]?.value||0)>.12,padDrift=!!(pad?.buttons?.[0]?.pressed||pad?.buttons?.[1]?.pressed);const steer=clamp((keys.KeyA||keys.ArrowLeft||held.left?1:0)-(keys.KeyD||keys.ArrowRight||held.right?1:0)+padSteer,-1,1),braking=!!(keys.KeyS||keys.ArrowDown||held.brake||padBrake),gas=!!(settings.touch||keys.KeyW||keys.ArrowUp||padGas),handbrake=!!keys.Space,driftButton=!!(keys.ShiftLeft||keys.ShiftRight||held.drift||padDrift||handbrake);
visualSteer=steer;brakeActive=braking||handbrake;isDrifting=!!(driftButton&&Math.abs(steer)>.12&&speed>16);const steeringGrip=isDrifting?2.15:10;const top=66;speed+=((gas?27:-10)-(braking?44:0)-(handbrake?12:0)-speed*(isDrifting?.13:.19))*dt;speed=clamp(speed,0,top);const steerRate=(1.72-Math.min(speed,80)*.009)*(isDrifting?1.62:1);heading+=steer*steerRate*dt*Math.min(speed/8,1);velocityHeading+=angle(heading-velocityHeading)*(1-Math.exp(-steeringGrip*dt));driftAngle=Math.abs(angle(heading-velocityHeading));player.position.x+=Math.sin(velocityHeading)*speed*dt;player.position.z+=Math.cos(velocityHeading)*speed*dt;
if(isDrifting&&driftAngle>.075){driftTime+=dt;chainGrace=1.25;flow=clamp(flow+(7+driftAngle*32)*dt,0,100);combo=clamp(1+Math.floor(flow/20)*.35+comboBonus,1,5);chainScore+=speed*driftAngle*13*combo*dt;emit(settings.reducedMotion?0:2,driftAngle>.32?0xff5f9c:0xffb464)}else{if(chainGrace>0){chainGrace-=dt;if(chainGrace<=0)bankChain()}driftTime=0}
const near=nearest(player.position,t);if(near.d>11.35){const p=at(near.t),dx=player.position.x-p.x,dz=player.position.z-p.z,d=Math.hypot(dx,dz);player.position.x=p.x+dx/d*11.35;player.position.z=p.z+dz/d*11.35;speed*=Math.exp(-1.8*dt);const roadHeading=yaw(near.t);if(Math.abs(angle(roadHeading-heading))<1.7){heading+=angle(roadHeading-heading)*dt*2;velocityHeading=heading}if(lastHit<=0){impact();beep(60,.1);emit(settings.reducedMotion?4:14,0xffaa44);shake=.25;lastHit=.35;loseChain('WALL HIT · CHAIN LOST')}cleanTime=0}else cleanTime+=dt;
progress+=advance(t,near.t);t=near.t;player.position.y=at(t).y;player.rotation.y=heading;player.userData.body.rotation.x=THREE.MathUtils.lerp(player.userData.body.rotation.x,curveSlope(t),dt*9);player.userData.body.rotation.z=THREE.MathUtils.lerp(player.userData.body.rotation.z,-steer*speed*.0018,dt*8);
const nextCP=Math.floor(Math.max(0,progress)*4);if(nextCP>checkpoint){checkpoint=nextCP;if(checkpoint%4!==0)toast('CHECKPOINT '+(checkpoint%4)+' / 3')}
if(Math.floor(progress)>lastLap&&progress<3){laps.push(time-lapStarted);lapStarted=time;lastLap=Math.floor(progress);toast('LAP '+(lastLap+1)+' / 3 · '+format(laps.at(-1)));beep(520,.18)}
const dist=district(Math.max(0,progress));if(sector!==dist.name){sector=dist.name;$('districtName').textContent=sector;$('districtHint').textContent=dist.hint}
const bend=curvature(t+.018);$('corner').textContent=Math.abs(angle(yaw(t)-heading))>2?'WRONG WAY':bend>.43?'HAIRPIN · BRAKE':bend>.20?'CORNER AHEAD':'';
for(const u of driftZones){if(circularDistance(u,t)*LENGTH<5&&near.d<5&&zoneCooldown<=0){zoneCooldown=2;if(isDrifting&&driftAngle>.12){const award=Math.round(250*combo);chainScore+=award;flow=clamp(flow+24,0,100);comboBonus=clamp(comboBonus+.5,0,2);toast('APEX LINK +'+award);beep(650,.15)}else toast('APEX ZONE · ENTER SIDEWAYS')}}
for(let i=0;i<3;i++){const bend=curvature(ai[i]+.014),pace=settings.difficulty==='expert'?54:settings.difficulty==='normal'?48:38,target=pace+i*1.4-Math.min(19,bend*40);aiSpeeds[i]+=(target-aiSpeeds[i])*(1-Math.exp(-dt*1.4));ai[i]+=aiSpeeds[i]*dt/LENGTH;const gap=advance(ai[i]-1,progress),attack=gap>-0.025&&gap<.025?Math.sign(i-1||1)*2.2:0,lane=(i-1)*4.5+Math.sin(ai[i]*18+i)*1.25+attack;alignCar(rivals[i],ai[i],lane);if(player.position.distanceTo(rivals[i].position)<2.8&&lastHit<=0){speed*=.8;lastHit=.5;shake=.16;impact();emit(settings.reducedMotion?3:9,0xffbd68);beep(95,.08);loseChain('CONTACT · CHAIN LOST')}}
skidMarks.update(player.position,heading,isDrifting&&settings.effects);if(progress>=3)finish()}
function animateCar(car,s,sliding,now,dt){for(const wheel of car.userData.wheels)wheel.rotateY(s*dt*1.8);for(const pivot of car.userData.wheelPivots){if(pivot.userData.front)pivot.rotation.y=THREE.MathUtils.lerp(pivot.rotation.y,car===player?visualSteer*.34:0,dt*9)}car.userData.brakeMaterial.emissiveIntensity=car===player&&brakeActive?4:1.3;for(const flame of car.userData.flames){flame.visible=sliding&&!settings.reducedMotion;flame.scale.y=sliding?.55+Math.sin(now*.08)*.12:0}}
function frame(now){requestAnimationFrame(frame);const rawDelta=Math.max(0,Math.min((now-last)/1000,.12)),dt=Math.min(rawDelta,.05);last=now;qualityTime+=rawDelta;qualityFrames++;if(settings.quality==='auto'&&autoQuality==='high'&&qualityTime>5){if(qualityFrames/qualityTime<42){autoQuality='low';config();toast('ADAPTIVE GRAPHICS · BATTERY MODE')}qualityTime=0;qualityFrames=0}let viewTrack=t;updateStartLights(countdown,state==='race');if(state==='race'){raceAccumulator+=rawDelta;while(raceAccumulator>=1/60&&state==='race'){updateRace(1/60);raceAccumulator-=1/60}hudAccumulator+=rawDelta;if(hudAccumulator>=.05){updateHud();hudAccumulator=0}show('countdown',countdown>0||time<.65);$('countdown').textContent=countdown>0?String(Math.min(3,Math.ceil(countdown))):'GO';toastTime-=rawDelta;if(toastTime<=0)show('toast',false);particlesStep(rawDelta);animateCar(player,speed,isDrifting,now,dt);rivals.forEach((r,i)=>animateCar(r,aiSpeeds[i],false,now,dt))}
music.setPhase(state==='race'||state==='settings'&&previous==='race'?'race':'intro',state==='settings');if(engine){engine.frequency.setTargetAtTime(42+speed*2.2,audio.currentTime,.08);engineGain.gain.setTargetAtTime(state==='race'&&soundEnabled?settings.volume/100*(.025+speed*.0003):0,audio.currentTime,.08);motor.frequency.setTargetAtTime(120+speed*(isDrifting?7:5),audio.currentTime,.06);motorGain.gain.setTargetAtTime(state==='race'&&soundEnabled?settings.volume/100*.015:0,audio.currentTime,.08);tyreGain?.gain.setTargetAtTime(state==='race'&&isDrifting&&soundEnabled?settings.volume/100*.055:0,audio.currentTime,.06)}
if(state==='race'||state==='settings'&&previous==='race'||state==='end'){const forward=new THREE.Vector3(Math.sin(heading),0,Math.cos(heading));const desired=player.position.clone().addScaledVector(forward,-11);desired.y+=5.3;if(state==='race'&&countdown>1.3){desired.add(new THREE.Vector3(Math.cos(heading)*3.8,-1.4,-Math.sin(heading)*3.8))}camera.position.lerp(desired,1-Math.exp(-7*dt));const look=player.position.clone().addScaledVector(forward,state==='race'&&countdown>1.3?5:15);look.y+=1.4;shake=Math.max(0,shake-dt);if(settings.effects&&!settings.reducedMotion&&shake>0){camera.position.x+=Math.sin(now*.15)*shake*.35;camera.position.y+=Math.cos(now*.11)*shake*.25}camera.lookAt(look);camera.fov=THREE.MathUtils.lerp(camera.fov,isDrifting&&!settings.reducedMotion?68:64,dt*4);camera.updateProjectionMatrix()}else{const u=wrap(now*.000012+.05),p=at(u),h=yaw(u);viewTrack=u;camera.position.set(p.x-Math.sin(h)*17,p.y+7,p.z-Math.cos(h)*17);camera.lookAt(at(u+.025));alignCar(player,u,2);rivals.forEach((r,i)=>alignCar(r,u+.01+i*.007,(i-1)*5));animateCar(player,20,false,now,dt)}
ambientCars.forEach((g,i)=>{g.position.set(290+i*12,48+i*9,((now*.022+i*110)%850)-420)});const quality=effectiveQuality(),effectsOn=settings.effects&&!settings.reducedMotion;atmosphere.update(camera,now,effectsOn&&!(viewTrack>.455&&viewTrack<.585),quality);postFX.render(scene,camera,quality==='high'&&effectsOn,isDrifting,now)}
config();alignCar(player,t,2);requestAnimationFrame(frame);
