// Moments on the lap clock: one named moment per district, two big movers and four vignettes per circuit.
// Built after batching so every part can animate. W is the world helper set passed from world.js.
export function buildMoments(W){
  const {THREE,scene,box,material,onTrack,at,yaw,wrap,level,cyan,pink,amber,dark,white,worldEvents,riskRoutes,LENGTH,skyActors}=W;
  const glow=(c,i)=>new THREE.MeshStandardMaterial({color:c,emissive:c,emissiveIntensity:i,roughness:.4});
  const fog=(c,o)=>new THREE.MeshBasicMaterial({color:c,transparent:true,opacity:o,depthWrite:false,side:THREE.DoubleSide});
  const M=[];// {name,district,t,lapMin,fired,update(now,ctx,ahead,near)}
  const dist=(a,b)=>{let d=b-a;d-=Math.round(d);return d};// signed lap fraction from a to b
  function moment(name,district,t,build,opts={}){const m={name,district,t,big:!!opts.big,lapMin:opts.lapMin||0,firedLap:-1,...build()};M.push(m);return m}
  const strips=(n,t0,dt,lane,y,color,w=1.2,h=.3,d=.3)=>Array.from({length:n},(_,i)=>{const g=onTrack(t0+i*dt);return box(w,h,d,lane,y,0,glow(color,.4),g)});
  const chase=(list,now,speed=6,gain=2.4)=>list.forEach((s,i)=>{s.material.emissiveIntensity=.3+Math.max(0,Math.sin(now*.001*speed-i*.9))*gain});

  if(level.id==='midnight'){
    moment('MARKET STEAM',1,.05,()=>{const vents=[-24,24,-24,24].map((lane,i)=>{const g=onTrack(.03+i*.014,lane);return box(3,1,3,0,2,0,fog(0xcfe6ff,.28),g)});return{update(now,ctx,ahead,near){vents.forEach((v,i)=>{const k=near?1:.25;v.scale.y=1+k*(2+Math.sin(now*.004+i)*1.5);v.position.y=2+v.scale.y*.5;v.material.opacity=.12+k*.2})}}});
    moment('SKYWAY BEACONS',2,.225,()=>{const beams=[.18,.27].map(t=>{const g=onTrack(t,16);const b=box(.6,.6,70,0,26,35,fog(0x9ff6ff,.16),g);return{g,b}});return{big:true,update(now,ctx,ahead,near){beams.forEach(({g,b},i)=>{const dx=ctx.x-g.position.x,dz=ctx.z-g.position.z;const want=near?Math.atan2(dx,dz)-g.rotation.y:now*.0003+i;b.rotation.y+=(want-b.rotation.y)*.05;b.rotation.x=near?-.35:-.15;b.material.opacity=near?.28:.12})}}},{big:true});
    moment('TUNNEL CHASE',3,.37,()=>{const s=strips(14,.318,.0082,0,9.8,0x50fff1,26,.16,.3);return{update(now,ctx,ahead,near){if(near)chase(s,now,9);else s.forEach(x=>x.material.emissiveIntensity=.3)}}});
    moment('GLASSHOUSE WAKE',4,.5,()=>{const s=[];for(let i=0;i<19;i+=2){const g=onTrack(.465+i*.009);for(const side of [-1,1])s.push(box(.3,16,.3,side*11.4,8,0,glow(0x50fff1,.3),g))}return{big:true,update(now,ctx,ahead,near){if(near){const p=(ctx.t-.465)/.17;s.forEach((x,i)=>{const k=i/2/10;x.material.emissiveIntensity=.3+Math.max(0,1-Math.abs(k-p)*6)*3})}else s.forEach(x=>x.material.emissiveIntensity=.3)}}},{big:true});
    moment('MAGLEV INBOUND',5,.7,()=>{const s=strips(10,.665,.017,-20,15.7,0xff408c,6,.12,1.2);return{update(now,ctx,ahead,near){if(ahead>0&&ahead<.06)chase(s,now,7);else chase(s,now,1.5,.6)}}});
    moment('DOCK CRANE',6,.9,()=>{const g=new THREE.Group();g.position.copy(at(.9,-46));g.position.y-=.1;scene.add(g);box(2,40,2,0,20,0,dark,g);const arm=box(40,1.5,1.5,14,40,0,material(0xd28241),g),lamp=box(.8,.8,.8,34,39,0,glow(0xff3b3b,2.5),g);return{arm,lamp,update(now,ctx,ahead,near){g.rotation.y=Math.sin(now*.00025)*.6;lamp.visible=Math.sin(now*.006)>0}}});
  }
  if(level.id==='floodline'){
    moment('HARBOUR HORN',1,.06,()=>{const lamps=[.02,.05,.08].map(t=>{const g=onTrack(t,-31);return box(1,1,1,0,11,-6,glow(0xffb95c,1.5),g)});return{update(now,ctx,ahead,near){lamps.forEach((l,i)=>l.material.emissiveIntensity=near?(Math.sin(now*.01+i)>0?3.5:.3):1.5)}}});
    moment('STORM FRONT',2,.25,()=>{const sheet=new THREE.Mesh(new THREE.PlaneGeometry(1800,900),fog(0xbfe6ff,0));sheet.position.set(0,320,-300);sheet.rotation.x=.2;scene.add(sheet);let next=4,flash=0;return{update(now,ctx,ahead,near){if(near&&ctx.time>next){next=ctx.time+2.5+Math.random()*4;flash=.25;worldEvents.push({text:'LIGHTNING',beep:180})}flash=Math.max(0,flash-.016);sheet.material.opacity=flash*(Math.random()>.5?1:.4)}}});
    moment('FLOODGATE',3,.45,()=>{const slabs=[.43,.455,.47].map(t=>{const g=onTrack(t);return box(30,8,1.2,0,-2,0,material(0x2b3f4c),g)});const strobes=[.415,.42].flatMap(t=>{const g=onTrack(t);return [-1,1].map(s=>box(.6,.6,.6,s*17,9,0,glow(0xffae5d,2),g))});let open=1;return{big:true,update(now,ctx,ahead,near){const want=(ahead>0&&ahead<.05)||near?1:0;open+=(want-open)*.03;slabs.forEach(s=>s.position.y=-2+open*0-(1-open)*-6);strobes.forEach((s,i)=>s.visible=ahead>0&&ahead<.05?Math.sin(now*.02+i*3)>0:true);if(ahead>0&&ahead<.02&&this.firedLap<ctx.lap){this.firedLap=ctx.lap;worldEvents.push({text:'FLOODGATE OPENING',beep:420})}}}},{big:true});
    moment('STORM SURGE',4,.58,()=>{const r=riskRoutes[0];const wave=box(16,2.2,10,0,0,0,fog(0x5fd8ff,.35));scene.add(wave);let u=-1;return{big:true,update(now,ctx,ahead,near){if(ctx.lap>=1&&near&&u<0){u=0;worldEvents.push({text:'STORM SURGE · CANAL BED',beep:240})}if(u>=0){u+=.004;const p=r.curve.getPointAt(Math.min(1,u));wave.position.set(p.x,p.y+1,p.z);wave.rotation.y=Math.atan2(r.curve.getTangentAt(Math.min(1,u)).x,r.curve.getTangentAt(Math.min(1,u)).z);wave.material.opacity=.35*(1-u);if(u>=1)u=-1}wave.visible=u>=0}}},{big:true,lapMin:1});
    moment('OVERFLOW',5,.75,()=>{const jets=[.72,.74,.76,.78].map((t,i)=>{const g=onTrack(t,(i%2?1:-1)*20);return box(1.2,6,1.2,0,3,0,fog(0xd9f4ff,.3),g)});return{update(now,ctx,ahead,near){jets.forEach((j,i)=>{const k=near?1:.4;j.scale.y=k*(.6+Math.abs(Math.sin(now*.003+i*1.1))*1.2);j.position.y=3*j.scale.y})}}});
    moment('PUMP PISTONS',6,.815,()=>{const pistons=[.795,.815,.835].map(t=>{const g=onTrack(t,-38);return box(3,6,3,0,16,0,material(0x4d6070),g)});return{update(now,ctx,ahead,near){const rate=near?.012:.003;pistons.forEach((p,i)=>p.position.y=16+Math.sin(now*rate+i*2)*2.5)}}});
  }
  if(level.id==='skyline'){
    moment('TOWER WAVE',1,.08,()=>{const s=[];for(let i=0;i<6;i++){const g=onTrack(.03+i*.02,(i%2?1:-1)*44);for(let y=6;y<60;y+=9)s.push(box(8,.5,8,0,y,0,glow(0xb9ff65,.3),g))}return{update(now,ctx,ahead,near){s.forEach((x,i)=>x.material.emissiveIntensity=.3+(near?Math.max(0,Math.sin(now*.004-(i%6)*.7)):0)*1.6)}}});
    moment('SHUTTLE CROSSING',2,.47,()=>{return{big:true,update(now,ctx,ahead,near){if(ahead>0&&ahead<.03&&this.firedLap<ctx.lap){this.firedLap=ctx.lap;worldEvents.push({text:'SHUTTLE CROSSING OVERHEAD',beep:520})}}}},{big:true});
    moment('CLOUD BREAK',3,.485,()=>{const flare=new THREE.Mesh(new THREE.PlaneGeometry(600,300),fog(0xe8e0ff,0));flare.position.set(0,40,0);scene.add(flare);return{update(now,ctx,ahead,near){flare.position.set(ctx.x,ctx.y+20,ctx.z-200);flare.material.opacity=near?.12+Math.max(0,Math.sin(now*.003))*.1:0}}});
    moment('HELI LIFT',4,.5,()=>{const g=onTrack(.5,-33);g.position.y+=1;const body=box(4,2,7,0,1.5,0,material(0x262a44),g),rotor=box(11,.15,.6,0,3,0,material(0x8a7dff,.5),g),tail=box(1,1,5,0,2,-5,dark,g),lamp=box(.5,.5,.5,0,3.4,0,glow(0xff5b5b,2.5),g);let lift=0,spin=0;return{big:true,update(now,ctx,ahead,near){const want=near||(ahead>-.03&&ahead<.04)?1:0;lift+=(want-lift)*.02;spin+=lift*.5;rotor.rotation.y=spin;g.position.y=at(.5,-33).y+1+lift*32;g.rotation.y=yaw(.5)+lift*.6;lamp.visible=Math.sin(now*.008)>0;if(want&&this.firedLap<ctx.lap&&lift>.3){this.firedLap=ctx.lap;worldEvents.push({text:'HELI LIFT-OFF',beep:300})}}}},{big:true});
    moment('ANTENNA STROBE',5,.75,()=>{const s=[.36,.55,.76].map(t=>{const g=onTrack(t,22);return box(1,1,1,0,44,0,glow(0xff5b5b,3),g)});return{update(now,ctx,ahead,near){s.forEach((x,i)=>x.visible=Math.sin(now*(near?.02:.005)+i*2)>.4)}}});
    moment('FINISH BOARD',6,.97,()=>{const g=onTrack(.985);const panel=box(18,3,.4,0,15,0,glow(0xb9ff65,.6),g);return{update(now,ctx,ahead,near){panel.material.emissive.setHex(Math.floor(now/900)%2?0xb9ff65:0x8a7dff);panel.material.emissiveIntensity=near?2:.6}}});
  }
  if(level.id==='blackout'){
    moment('SODIUM FLICKER',1,.06,()=>{const heads=[];for(let i=0;i<8;i++){const g=onTrack(.02+i*.012);for(const side of [-1,1])heads.push(box(1.3,.55,1,side*14.4,8.3,0,glow(0xffae5d,2.6),g))}return{update(now,ctx,ahead,near){heads.forEach((h,i)=>h.material.emissiveIntensity=near&&Math.sin(now*.03*(1+i%3)+i)>.6?.2:2.6)}}});
    moment('TRANSFORMER ARC',2,.2,()=>{const arcs=[];for(let i=0;i<5;i++){const g=onTrack(.12+i*.006,36);arcs.push(box(22,.15,.15,0,5.7,(i-2)*3,glow(0xffffff,3),g))}return{big:true,update(now,ctx,ahead,near){arcs.forEach((a,i)=>{a.visible=near&&Math.random()>.7;a.scale.x=.4+Math.random()*.8;a.position.x=(Math.random()-.5)*8});if(near&&this.firedLap<ctx.lap){this.firedLap=ctx.lap;worldEvents.push({text:'ARC FLASH · SUBSTATION',beep:160})}}}},{big:true});
    moment('STADIUM WAVE',3,.3,()=>{const s=[];for(let i=0;i<12;i++){const g=onTrack(.27+i*.005,(i%2?1:-1)*24);s.push(box(6,.4,.4,0,6,0,glow(0xff3b68,.4),g))}return{update(now,ctx,ahead,near){if(near)chase(s,now,8,2.2);else chase(s,now,2,.5)}}});
    moment('ROLLING BLACKOUT',4,.55,()=>{const strips=[];for(let i=0;i<10;i++){const g=onTrack(.5+i*.012);for(const side of [-1,1])strips.push(box(.3,.3,6,side*17.2,1.1,0,glow(0xffae5d,0),g))}return{big:true,update(now,ctx,ahead,near){strips.forEach((s,i)=>s.material.emissiveIntensity=ctx.blackout?2+Math.sin(now*.01+i)*.5:0)}}},{big:true});
    moment('UNDERPASS SIREN',5,.63,()=>{const s=[.6,.62,.64,.66].map(t=>{const g=onTrack(t);return box(.8,.5,.8,0,7,0,glow(0xff2d2d,2.4),g)});return{update(now,ctx,ahead,near){s.forEach((x,i)=>x.visible=(ahead>0&&ahead<.04)||near?Math.sin(now*.015+i*1.5)>0:false)}}});
    moment('PYLON HUM',6,.9,()=>{const s=[.81,.95].flatMap(t=>{const g=onTrack(t);return [-1,0,1].map(c=>box(.4,.4,.4,c*18,31.2,c*1.6,glow(0x9a9088,.5),g))});return{update(now,ctx,ahead,near){s.forEach((x,i)=>x.material.emissiveIntensity=.5+(near?Math.max(0,Math.sin(now*.02+i)):0)*2)}}});
  }
  if(level.id==='solara'){
    moment('MIRROR GLINT',1,.08,()=>{const s=[];for(let i=0;i<10;i++){const g=onTrack(.02+i*.012,(i%2?1:-1)*42);const p=box(12,.35,7,0,3.6,0,glow(0xffd166,.2),g);p.rotation.x=-.32;s.push(p)}return{update(now,ctx,ahead,near){s.forEach((x,i)=>x.material.emissiveIntensity=near&&Math.sin(now*.004-i*.8)>.92?3:.2)}}});
    moment('DUST STORM',2,.25,()=>{const walls=[0,1,2].map(i=>{const m=new THREE.Mesh(new THREE.PlaneGeometry(160,60),fog(0xd08a4e,0));scene.add(m);return m});let x=-1;return{big:true,update(now,ctx,ahead,near){if(ctx.lap>=1&&ahead>0&&ahead<.05&&x<0){x=0;worldEvents.push({text:'DUST FRONT AHEAD',beep:200})}if(x>=0){x+=.003;const base=at(.25,0);walls.forEach((w,i)=>{w.position.set(base.x+(x-.5)*300+i*40,base.y+25,base.z+(i-1)*60);w.rotation.y=yaw(.25)+Math.PI/2;w.material.opacity=.35*Math.sin(Math.min(1,x)*Math.PI)});if(x>=1)x=-1}walls.forEach(w=>w.visible=x>=0)}}},{big:true,lapMin:1});
    moment('AQUEDUCT SPILL',3,.48,()=>{const sheet=[.44,.5].map(t=>{const g=onTrack(t,-16);return box(3,14,.6,0,10,0,fog(0x9fd8ff,.25),g)});return{update(now,ctx,ahead,near){sheet.forEach((s,i)=>{s.material.opacity=near?.3+Math.sin(now*.01+i)*.1:.15})}}});
    moment('ROCKFALL',4,.47,()=>{const rocks=[0,1,2].map(i=>{const r=new THREE.Mesh(new THREE.DodecahedronGeometry(1.6+i*.4),material(0x6f382e));scene.add(r);return r});let k=-1;return{big:true,update(now,ctx,ahead,near){if(ahead>0&&ahead<.03&&k<0&&this.firedLap<ctx.lap){k=0;this.firedLap=ctx.lap;worldEvents.push({text:'ROCKFALL · CANYON',beep:120})}if(k>=0){k+=.012;rocks.forEach((r,i)=>{const p=at(.47+i*.012,20+8*(1-k));r.position.set(p.x,p.y+22*(1-k)*(1-k)+1.6,p.z);r.rotation.x+=.15;r.rotation.z+=.1});if(k>=1.2)k=-1}rocks.forEach(r=>r.visible=k>=0)}}},{big:true});
    moment('CROWN FLARE',5,.75,()=>{const beam=box(.8,.8,120,0,0,0,fog(0xffd166,.18));scene.add(beam);return{update(now,ctx,ahead,near){const p=at(.75,21);beam.position.set(p.x,p.y+12,p.z);beam.rotation.y=now*.0006;beam.material.opacity=near?.28:.1}}});
    moment('DUST DEVIL',6,.9,()=>{const g=new THREE.Group();scene.add(g);for(let i=0;i<5;i++){const b=box(3+i,3,3+i,0,i*3,0,fog(0xd08a4e,.18),g);b.rotation.y=i}return{update(now,ctx,ahead,near){const p=at(.88+Math.sin(now*.0002)*.03,36);g.position.set(p.x,p.y,p.z);g.rotation.y=now*.004;g.children.forEach((c,i)=>c.rotation.y=now*.003*(i+1))}}});
  }
  if(level.id==='cryoline'){
    moment('ICE CRACK',1,.155,()=>{const s=[];for(let i=0;i<6;i++){const g=onTrack(.125+i*.012,(i%2?1:-1)*5);const c=box(.2,.06,9,0,.12,0,glow(0x9be8ff,.5),g);c.rotation.y=(i%2?1:-1)*.5;s.push(c)}return{update(now,ctx,ahead,near){s.forEach((x,i)=>x.material.emissiveIntensity=near?.5+Math.max(0,Math.sin(now*.008-i))*3:.3)}}});
    moment('CALVING',2,.3,()=>{const g=onTrack(.32,-46);const block=box(10,18,8,0,9,0,material(0x8ecbd5,.12),g);let k=-1;return{big:true,update(now,ctx,ahead,near){if(ahead>0&&ahead<.04&&k<0&&this.firedLap<ctx.lap){k=0;this.firedLap=ctx.lap;worldEvents.push({text:'GLACIER CALVING',beep:110})}if(k>=0){k+=.01;block.rotation.x=Math.min(1.4,k*1.6);block.position.z=-k*6;if(k>=2){k=-1;block.rotation.x=0;block.position.z=0}}}}},{big:true});
    moment('SNOW SQUALL',3,.45,()=>{const gust=new THREE.Mesh(new THREE.PlaneGeometry(200,40),fog(0xffffff,0));scene.add(gust);let x=-1;return{update(now,ctx,ahead,near){if(near&&x<0)x=0;if(x>=0){x+=.006;const p=at(.45,0);gust.position.set(p.x+(x-.5)*260,p.y+12,p.z);gust.rotation.y=yaw(.45)+Math.PI/2;gust.material.opacity=.22*Math.sin(Math.min(1,x)*Math.PI);if(x>=1)x=-1}gust.visible=x>=0}}});
    moment('VAULT CHASE',4,.56,()=>{const s=strips(18,.51,.006,0,12.6,0x9bdce8,28,.14,.4);return{update(now,ctx,ahead,near){if(near)chase(s,now,10,2.4);else s.forEach(x=>x.material.emissiveIntensity=.4)}}});
    moment('LAUNCH',5,.73,()=>{const g=onTrack(.735,44);const rocket=box(3,22,3,0,11,0,material(0xd8fbff),g),nose=box(2,4,2,0,24,0,material(0xa983ff,.5),g),flame=box(3.5,10,3.5,0,-5,0,fog(0xffc265,0),g),pad=box(14,1,14,0,.4,0,dark,g);let h=-1;return{big:true,update(now,ctx,ahead,near){if(ctx.lap>=2&&ahead>-.02&&ahead<.05&&h<0&&this.firedLap<ctx.lap){h=0;this.firedLap=ctx.lap;worldEvents.push({text:'LAUNCH · CRAWLER YARD',beep:90})}if(h>=0){h+=.004;[rocket,nose,flame].forEach(m=>m.position.y=(m===rocket?11:m===nose?24:-5)+h*h*400);flame.material.opacity=.7*(1-h*.5);flame.scale.y=1+Math.random()*.6;if(h>=1.5){h=-1;flame.material.opacity=0;[rocket,nose,flame].forEach(m=>m.position.y=(m===rocket?11:m===nose?24:-5))}}}}},{big:true,lapMin:2});
    moment('AURORA SURGE',6,.92,()=>{return{update(now,ctx,ahead,near){(skyActors||[]).forEach((r,i)=>{r.material.opacity=(near?.2:.075)+i*.025+Math.sin(now*.0004+i)*.018})}}});
  }
  return{
    list:M,
    update(now,ctx){if(!ctx)return;for(const m of M){const ahead=dist(ctx.t,m.t),near=Math.abs(ahead)*LENGTH<70||(ahead>0&&ahead*LENGTH<Math.max(40,ctx.speed*2));if(m.update)m.update(now,ctx,ahead,near)}}
  };
}
